name: Run KrypNews Script Daily
on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs every day at midnight UTC
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trigger Vercel Function
        run: |
          curl -X POST https://<your-vercel-url>/api/run_script
